import { Math } from '@vicons/tabler';
import { defineTool } from '../tool';

export const tool = defineTool({
  name: '数学计算器',
  path: '/math-evaluator',
  description: '用于计算数学表达式的计算器。支持 sqrt、cos、sin、abs 等函数。',
  keywords: [
    '数学',
    '计算器',
    '表达式',
    '函数',
    'abs',
    'acos',
    'acosh',
    'acot',
    'acoth',
    'acsc',
    'acsch',
    'asec',
    'asech',
    'asin',
    'asinh',
    'atan',
    'atan2',
    'atanh',
    'cos',
    'cosh',
    'cot',
    'coth',
    'csc',
    'csch',
    'sec',
    'sech',
    'sin',
    'sinh',
    'sqrt',
    'tan',
    'tanh',
  ],
  component: () => import('./math-evaluator.vue'),
  icon: Math,
});
