export const allLanguagesAndCountries = [
  '(International)',
  '(France)',
  '(Belgium)',
  '(Switzerland)',
  '(Québec)',
  '(Germany, 2022)',
  '(Austria)',
  '(Germany, informal, 2022)',
  '(Netherlands)',
  'Italian',
  'Spanish',
  '(Brazil)',
  '(Portugal)',
  'Swedish',
  'Danish',
  'Norwegian',
  'Finnish',
  'Turkish',
  'Romanian',
  'Czech',
  'Yugoslav',
  'Serbian',
  'Slovene',
  'Russian',
  'Korean',
  'Greek',
  'Japanese',
];
