<script setup lang="ts">
import { withDefaultOnError } from '../../utils/defaults';
import {
  getTocMarkdown,
} from './markdown-toc-generator.service';
import { useQueryParamOrStorage } from '@/composable/queryParams';

const markdown = ref('');
const generateAnchors = useQueryParamOrStorage({ name: 'anchors', storageName: 'md-toc-gen:anchors', defaultValue: true });
const indentChars = useQueryParamOrStorage({ name: 'bullets', storageName: 'md-toc-gen:bullets', defaultValue: '-*+' });
const indentSpaces = ref(2);
const maxLevel = useQueryParamOrStorage({ name: 'max', storageName: 'md-toc-gen:max', defaultValue: -1 });
const anchorPrefix = useQueryParamOrStorage({ name: 'prefix', storageName: 'md-toc-gen:prefix', defaultValue: '' });
const concatSpaces = useQueryParamOrStorage({ name: 'concat', storageName: 'md-toc-gen:concat', defaultValue: true });
const commentStyle = useQueryParamOrStorage({ name: 'comment', storageName: 'md-toc-gen:comment', defaultValue: 'html' });

const markdownWithTOC = computed(() => withDefaultOnError(() => {
  return getTocMarkdown({
    markdown: markdown.value,
    anchorPrefix: anchorPrefix.value,
    commentStyle: commentStyle.value as ('html' | 'liquid'),
    concatSpaces: concatSpaces.value,
    generateAnchors: generateAnchors.value,
    indentChars: indentChars.value,
    indentSpaces: indentSpaces.value,
    maxLevel: maxLevel.value,
  });
}, ''));
</script>

<template>
  <div>
    <c-card title="Options" mb-2>
      <n-form-item label="Generate Anchors" label-placement="left">
        <n-checkbox v-model:checked="generateAnchors" mr-2 />
      </n-form-item>

      <c-input-text
        v-model:value="indentChars"
        label="Bullet Chars"
        placeholder="Bullet Chars"
        mb-2
      />

      <n-form-item label="Indents: " label-placement="left">
        <n-input-number v-model:value="indentSpaces" placeholder="Indents..." :max="10" :min="1" w-full />
      </n-form-item>

      <n-form-item label="Max Heading Level: " label-placement="left">
        <n-input-number v-model:value="maxLevel" placeholder="Max Heading Level..." :max="6" :min="-1" w-full />
      </n-form-item>

      <c-input-text
        v-model:value="anchorPrefix"
        label="Anchors Prefix"
        placeholder="Anchors Prefix"
        mb-2
      />

      <n-form-item label="Concat Spaces" label-placement="left">
        <n-checkbox v-model:checked="concatSpaces" mr-2 />
      </n-form-item>

      <c-select
        v-model:value="commentStyle"
        label="Comment Styles"
        :options="['html', 'liquid']"
        placeholder="Comment Styles"
      />
    </c-card>

    <c-card title="Input markdown" mb-2>
      <n-p>You can paste a document with existing TOC (generated by this tool) or add a <code>[TOC]</code> marker in your document (on a single line)</n-p>
      <c-input-text
        v-model:value="markdown"
        placeholder="Put your markdown here..."
        multline
        rows="8"
        mb-2
        mt-2
      />
    </c-card>

    <c-card title="Output markdown with TOC" mb-2>
      <textarea-copyable
        language="markdown"
        :value="markdownWithTOC"
      />
    </c-card>
  </div>
</template>
