<script setup lang="ts">
import UnitsConverter from '@/components/UnitsConverter.vue';

const supportedUnits = {
  'm³': 'cubic meter/stere',
  'Pm³': 'cubic petameter',
  'Tm³': 'cubic terameter',
  'Gm³': 'cubic gigameter',
  'Mm³': 'cubic megameter',
  'km³': 'cubic kilometer',
  'hm³': 'cubic hectometer',
  'dam³': 'cubic decameter',
  'dm³': 'cubic decimeter',
  'cm³': 'cubic centimeter',
  'mm³': 'cubic millimeter',
  'µm³': 'cubic micrometer',
  'nm³': 'cubic nanometer',
  'pm³': 'cubic picometer',
  'fm³': 'cubic femtometer',
  'L': 'liter',
  'Pl': 'petaliter',
  'Tl': 'teraliter',
  'Gl': 'gigaliter',
  'Ml': 'megaliter',
  'kL': 'kiloliter',
  'hL': 'hectoliter',
  'daL': 'decaliter',
  'dL': 'deciliter',
  'cL': 'centiliter',
  'mL': 'milliliter',
  'µL': 'microliter',
  'nL': 'nanoliter',
  'pL': 'picoliter',
  'fL': 'femtoliter',
  'mi³': 'cubic mile',
  'ac ft': 'acre-foot',
  'yd³': 'cubic yard',
  'ft³': 'cubic foot',
  'board feet': 'board feet',
  'in³': 'cubic inch',
  'MTON': 'measurement ton',
  'imp bbl': 'imperial barrel',
  'imp bsh': 'imperial bushel',
  'pk': 'imperial peck',
  'imp gal': 'imperial gallon',
  'imp qt': 'imperial quart',
  'imp pt': 'imperial pint',
  'imp fl oz': 'imperial fluid ounce',
  'tsp': 'teaspoon',
  'tbsp': 'tablespoon',
  'fl oz': 'US fluid ounce',
  'c': 'cup',
  'US lc': 'US legal cup',
  'pt': 'US liquid pint',
  'qt': 'US liquid quart',
  'gal': 'US liquid gallon',
  'US bsh': 'US bushel',
  'US pk': 'US peck',
  'US dry gal': 'US dry gallon',
  'US dry bbl': 'US dry barrel',
  'US dry qt': 'US dry quart',
  'US dry pt': 'US dry pint',
};
</script>

<template>
  <UnitsConverter default-unit="m³" :supported-units="supportedUnits" label-width="150px" />
</template>
