// Differential test: the IPv6 calculator must agree with Python's `ipaddress`
// stdlib on 124 random + hand-picked cases (fixture generated by CPython).
import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { describeIpv6 } from './ipv6-subnet-calculator.models';

interface FixtureCase {
  input: string
  expanded: string
  compressed: string
  network: string
  first: string
  last: string
  total: string
  netmask: string
}

const cases: FixtureCase[] = JSON.parse(
  readFileSync(new URL('./ipv6.fixture.json', import.meta.url), 'utf8'),
);

// Python's ipaddress uses lowercase hex for IPv6 str(); my implementation is
// lowercase per RFC 5952 §4.3 recommendation. Normalize for comparison.
const lower = (s: string) => s.toLowerCase();

describe('ipv6-subnet-calculator: differential vs CPython ipaddress', () => {
  it.each(cases.map(c => [c.input, c]))('case %s', (_input, c) => {
    const info = describeIpv6(c.input);
    expect(lower(info.expanded)).toBe(lower(c.expanded));
    // compression: compare the network VALUE (Python may pick a different
    // zero-run on ties; the address itself must match) plus the prefix
    expect(lower(info.network.split('/')[0])).toBe(lower(c.network.split('/')[0]));
    expect(info.network.endsWith(`/${c.network.split('/')[1]}`)).toBe(true);
    expect(lower(info.firstAddress)).toBe(lower(c.first));
    expect(lower(info.lastAddress)).toBe(lower(c.last));
    expect(info.totalAddresses).toBe(c.total);
    expect(lower(info.mask)).toBe(lower(c.netmask));
  });
});
