import { describe, expect, it } from 'vitest';
import { handleArgon2idRequest } from './argon2id.worker-handler';
import { parseArgon2idMessage } from './argon2id.worker.protocol';

// Generated by the independent @phc/argon2 implementation and published in
// its README for password "password".
const INDEPENDENT_PHC = '$argon2id$v=19$m=4096,t=3,p=1$PcEZHj1maR/+ZQynyJHWZg$2jEN4xcww7CYp1jakZB1rxbYsZ55XH2HgjYRtdZtubI';

describe('Argon2id worker handler', () => {
  it('verifies an independent PHC vector and rejects the wrong password', async () => {
    const matching = await handleArgon2idRequest({ jobId: 3, task: { operation: 'verify', password: 'password', phc: INDEPENDENT_PHC } });
    const different = await handleArgon2idRequest({ jobId: 4, task: { operation: 'verify', password: 'wrong', phc: INDEPENDENT_PHC } });
    expect(matching).toMatchObject({ jobId: 3, type: 'result', result: { operation: 'verify', matches: true } });
    expect(different).toMatchObject({ jobId: 4, type: 'result', result: { operation: 'verify', matches: false } });
    parseArgon2idMessage(matching);
    parseArgon2idMessage(different);
  });

  it('hashes a fixed-salt bounded task without echoing the password', async () => {
    const message = await handleArgon2idRequest({ jobId: 5, task: { operation: 'hash', password: 'private-password', salt: new Uint8Array(16).fill(9), memoryKiB: 32, iterations: 1, parallelism: 1, hashLength: 16 } });
    expect(message).toMatchObject({ jobId: 5, type: 'result', result: { operation: 'hash', memoryKiB: 32, iterations: 1, parallelism: 1, hashLength: 16 } });
    expect(JSON.stringify(message)).not.toContain('private-password');
    parseArgon2idMessage(message);
  });

  it('returns only static errors without reflecting attacker-controlled input', async () => {
    const secret = 'do-not-reflect-this-value';
    const message = await handleArgon2idRequest({ jobId: 6, task: { operation: 'verify', password: secret, phc: '$argon2id$v=19$m=999999999,t=3,p=1$bad$bad' } });
    expect(message).toEqual({ jobId: 6, type: 'error', code: 'input-limit', message: 'Password, PHC string, salt, or Argon2id parameters exceed the local safety limits.' });
    expect(JSON.stringify(message)).not.toContain(secret);
  });
});
