name: Update Version on Branch Creation

on:
  create:
    # This will trigger the workflow when branches or tags are created.

jobs:
  update-version:
    runs-on: ubuntu-latest
    if: github.event.ref_type == 'branch' && github.ref_name != 'main' && github.ref_name != 'master'
    steps:
      - name: Checkout code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          ref: ${{ github.ref }}
      
      - name: Set up Node.js
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3
        with:
          node-version: '20'
          
      - name: Update package.json version
        run: |
          jq '.version = "${{ github.ref_name }}"' package.json > temp.json && mv temp.json package.json
          
      - name: Commit and Push
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add package.json
          git commit -m "Update version to ${{ github.ref_name }}"
          git push origin ${{ github.ref_name }}
