/* eslint-disable import/order -- generated imports mix packages, Vite virtual modules, and local SVGs */
// This file is generated by scripts/generate-tool-registry.mjs. Do not edit manually.
import { ArrowsShuffle as ToolIcon0, Certificate as ToolIcon10, Key as ToolIcon11, FileCertificate as ToolIcon13, Calendar as ToolIcon14, ArrowsLeftRight as ToolIcon15, LetterX as ToolIcon16, FileDigit as ToolIcon17, TextWrap as ToolIcon18, Palette as ToolIcon19, Fingerprint as ToolIcon2, LetterCaseToggle as ToolIcon20, Speakerphone as ToolIcon21, Binary as ToolIcon22, Braces as ToolIcon23, List as ToolIcon24, Markdown as ToolIcon26, Link as ToolIcon27, Code as ToolIcon28, Unlink as ToolIcon29, SortDescendingNumbers as ToolIcon3, DeviceDesktop as ToolIcon30, Tags as ToolIcon32, DeviceMobile as ToolIcon33, World as ToolIcon34, Keyboard as ToolIcon35, Edit as ToolIcon37, Browser as ToolIcon38, EyeOff as ToolIcon4, Mailbox as ToolIcon41, Qrcode as ToolIcon42, Scan as ToolIcon43, Camera as ToolIcon45, BrandGit as ToolIcon46, Terminal2 as ToolIcon47, SettingsAutomation as ToolIcon48, FileText as ToolIcon49, Hash as ToolIcon5, Database as ToolIcon50, FileSearch as ToolIcon52, Server as ToolIcon53, Alarm as ToolIcon54, FileCheck as ToolIcon55, FileInvoice as ToolIcon56, BrandDocker as ToolIcon57, Mail as ToolIcon58, Language as ToolIcon59, LockSquare as ToolIcon6, BrandJavascript as ToolIcon60, Api as ToolIcon61, Devices as ToolIcon64, BuildingFactory as ToolIcon65, MapSearch as ToolIcon66, Math as ToolIcon67, Hourglass as ToolIcon68, Percentage as ToolIcon69, Lock as ToolIcon7, Temperature as ToolIcon71, FileDiff as ToolIcon73, MoodSmile as ToolIcon74, Artboard as ToolIcon76, Phone as ToolIcon79, AlignJustified as ToolIcon8 } from '@vicons/tabler';
import { PasswordRound as ToolIcon31, AbcRound as ToolIcon36, HttpRound as ToolIcon39, CompareArrowsRound as ToolIcon40, ImageOutlined as ToolIcon44, AccountTreeOutlined as ToolIcon51, RouterOutlined as ToolIcon62, UnfoldMoreOutlined as ToolIcon63, TimerOutlined as ToolIcon70, SpeedFilled as ToolIcon72, TableChartOutlined as ToolIcon77, GridOnOutlined as ToolIcon78, ShortTextRound as ToolIcon9 } from '@vicons/material';
import ToolIcon1 from '~icons/mdi/form-textbox-password';
import ToolIcon12 from '~icons/mdi/file-certificate-outline';
import ToolIcon25 from '~icons/mdi/code-brackets';
import ToolIcon75 from './numeronym-generator/n7m-icon.svg?component';
import ToolIcon80 from '~icons/mdi/bank';
import { defineTool } from './tool';
import type { ToolCategory } from './tools.types';
import { codesByCategories } from './http-status-codes/http-status-codes.constants';
import { translate } from '@/plugins/i18n.plugin';

const tool0 = defineTool({
  name: translate('tools.token-generator.title'),
  path: '/token-generator',
  description: translate('tools.token-generator.description'),
  keywords: ['token', 'random', 'string', 'alphanumeric', 'symbols', 'number', 'letters', 'lowercase', 'uppercase', 'password', 'batch', 'custom alphabet', 'denied characters'],
  component: () => import('./token-generator/token-generator.tool.vue'),
  icon: ToolIcon0,
});

const tool1 = defineTool({
  name: translate('tools.passphrase-generator.title'),
  path: '/passphrase-generator',
  description: translate('tools.passphrase-generator.description'),
  keywords: ['passphrase', 'password', 'diceware', 'entropy', 'wordlist', 'web crypto'],
  component: () => import('./passphrase-generator/passphrase-generator.vue'),
  icon: ToolIcon1,
});

const tool2 = defineTool({
  name: translate('tools.nanoid-generator.title'),
  path: '/nanoid-generator',
  description: translate('tools.nanoid-generator.description'),
  keywords: ['nanoid', 'nano id', 'generator', 'random', 'id', 'identifier', 'unique', 'url safe', 'entropy', 'collision'],
  component: () => import('./nanoid-generator/nanoid-generator.vue'),
  icon: ToolIcon2,
});

const tool3 = defineTool({
  name: translate('tools.uuid-generator.title'),
  path: '/uuid-generator',
  description: translate('tools.uuid-generator.description'),
  keywords: ['uuid', 'v4', 'random', 'id', 'alphanumeric', 'identity', 'token', 'string', 'identifier', 'unique', 'v1', 'v3', 'v5', 'v6', 'v7', 'nil', 'objectid', 'snowflake'],
  component: () => import('./uuid-generator/uuid-generator.vue'),
  icon: ToolIcon2,
});

const tool4 = defineTool({
  name: translate('tools.ulid-generator.title'),
  path: '/ulid-generator',
  description: translate('tools.ulid-generator.description'),
  keywords: ['ulid', 'generator', 'random', 'id', 'alphanumeric', 'identity', 'token', 'string', 'identifier', 'unique'],
  component: () => import('./ulid-generator/ulid-generator.vue'),
  icon: ToolIcon3,
  createdAt: new Date('2023-09-11'),
});

const tool5 = defineTool({
  name: translate('tools.hash-text.title'),
  path: '/hash-text',
  description: translate('tools.hash-text.description'),
  keywords: [
    'hash',
    'digest',
    'crypto',
    'security',
    'text',
    'MD5',
    'SHA1',
    'SHA256',
    'SHA224',
    'SHA512',
    'SHA384',
    'SHA3',
    'RIPEMD160',
  ],
  component: () => import('./hash-text/hash-text.vue'),
  icon: ToolIcon4,
  redirectFrom: ['/hash'],
});

const tool6 = defineTool({
  name: translate('tools.file-hash.title'),
  path: '/file-hash',
  description: translate('tools.file-hash.description'),
  keywords: [
    'file',
    'hash',
    'checksum',
    'digest',
    'SHA-1',
    'SHA-256',
    'SHA-384',
    'SHA-512',
    'SHA3-256',
    'BLAKE3',
    'MD5',
    'integrity',
  ],
  component: () => import('./file-hash/file-hash.vue'),
  icon: ToolIcon5,
});

const tool7 = defineTool({
  name: translate('tools.bcrypt.title'),
  path: '/bcrypt',
  description: translate('tools.bcrypt.description'),
  keywords: ['bcrypt', 'hash', 'compare', 'password', 'salt', 'round', 'storage', 'crypto'],
  component: () => import('./bcrypt/bcrypt.vue'),
  icon: ToolIcon6,
});

const tool8 = defineTool({
  name: translate('tools.argon2id-hash-verify.title'),
  path: '/argon2id-hash-verify',
  description: translate('tools.argon2id-hash-verify.description'),
  keywords: ['argon2', 'argon2id', 'password', 'hash', 'verify', 'phc', 'wasm', 'salt', 'kdf'],
  component: () => import('./argon2id-hash-verify/argon2id-hash-verify.vue'),
  icon: ToolIcon2,
});

const tool9 = defineTool({
  name: translate('tools.devops-secret-helper.title'),
  path: '/devops-secret-helper',
  description: translate('tools.devops-secret-helper.description'),
  keywords: ['Ansible Vault', 'AES256', 'htpasswd', 'Apache', 'bcrypt', 'DevOps', 'secret'],
  component: () => import('./devops-secret-helper/devops-secret-helper.vue'),
  icon: ToolIcon7,
});

const tool10 = defineTool({
  name: translate('tools.aes-gcm-envelope.title'),
  path: '/aes-gcm-envelope',
  description: translate('tools.aes-gcm-envelope.description'),
  keywords: ['aes', 'gcm', 'pbkdf2', 'authenticated encryption', 'file encryption', 'envelope', 'web crypto'],
  component: () => import('./aes-gcm-envelope/aes-gcm-envelope.vue'),
  icon: ToolIcon7,
});

const tool11 = defineTool({
  name: translate('tools.encryption.title'),
  path: '/encryption',
  description: translate('tools.encryption.description'),
  keywords: ['cypher', 'encipher', 'text', 'AES', 'TripleDES', 'Rabbit', 'RC4'],
  component: () => import('./encryption/encryption.vue'),
  icon: ToolIcon7,
  redirectFrom: ['/cypher'],
});

const tool12 = defineTool({
  name: translate('tools.bip39-generator.title'),
  path: '/bip39-generator',
  description: translate('tools.bip39-generator.description'),
  keywords: ['BIP39', 'passphrase', 'generator', 'mnemonic', 'entropy'],
  component: () => import('./bip39-generator/bip39-generator.vue'),
  icon: ToolIcon8,
});

const tool13 = defineTool({
  name: translate('tools.hmac-generator.title'),
  path: '/hmac-generator',
  description: translate('tools.hmac-generator.description'),
  keywords: ['hmac', 'generator', 'MD5', 'SHA1', 'SHA256', 'SHA224', 'SHA512', 'SHA384', 'SHA3', 'RIPEMD160', 'hex key', 'base64 key', 'RFC 4231'],
  component: () => import('./hmac-generator/hmac-generator.vue'),
  icon: ToolIcon9,
});

const tool14 = defineTool({
  name: translate('tools.rsa-key-pair-generator.title'),
  path: '/rsa-key-pair-generator',
  description: translate('tools.rsa-key-pair-generator.description'),
  keywords: ['rsa', 'key', 'pair', 'generator', 'public', 'private', 'secret', 'ssh', 'pem'],
  component: () => import('./rsa-key-pair-generator/rsa-key-pair-generator.vue'),
  icon: ToolIcon10,
});

const tool15 = defineTool({
  name: translate('tools.ed25519-key-workspace.title'),
  path: '/ed25519-key-workspace',
  description: translate('tools.ed25519-key-workspace.description'),
  keywords: ['ed25519', 'ssh', 'key', 'public', 'private', 'pkcs8', 'spki', 'fingerprint'],
  component: () => import('./ed25519-key-workspace/ed25519-key-workspace.vue'),
  icon: ToolIcon11,
});

const tool16 = defineTool({
  name: translate('tools.certificate-inspector.title'),
  path: '/certificate-inspector',
  description: translate('tools.certificate-inspector.description'),
  keywords: ['certificate', 'x509', 'pem', 'der', 'csr', 'pkcs10', 'public key', 'fingerprint', 'tls'],
  component: () => import('./certificate-inspector/certificate-inspector.vue'),
  icon: ToolIcon2,
});

const tool17 = defineTool({
  name: translate('tools.password-strength-analyser.title'),
  path: '/password-strength-analyser',
  description: translate('tools.password-strength-analyser.description'),
  keywords: ['password', 'strength', 'analyser', 'and', 'crack', 'time', 'estimation', 'brute', 'force', 'attack', 'entropy', 'cracking', 'hash', 'hashing', 'algorithm', 'algorithms', 'md5', 'sha1', 'sha256', 'sha512', 'bcrypt', 'scrypt', 'argon2', 'argon2id', 'argon2i', 'argon2d'],
  component: () => import('./password-strength-analyser/password-strength-analyser.vue'),
  icon: ToolIcon1,
  createdAt: new Date('2023-06-24'),
});

const tool18 = defineTool({
  name: translate('tools.pdf-signature-checker.title'),
  path: '/pdf-signature-checker',
  description: translate('tools.pdf-signature-checker.description'),
  keywords: ['pdf', 'signature', 'checker', 'verify', 'validate', 'sign'],
  component: () => import('./pdf-signature-checker/pdf-signature-checker.vue'),
  icon: ToolIcon12,
  createdAt: new Date('2023-12-09'),
});

const tool19 = defineTool({
  name: translate('tools.pkcs12-pem-workspace.title'),
  path: '/pkcs12-pem-workspace',
  description: translate('tools.pkcs12-pem-workspace.description'),
  keywords: ['PKCS12', 'PKCS#12', 'PFX', 'P12', 'PEM', 'certificate', 'public key', 'CSR', 'X509', 'inspect', 'convert'],
  component: () => import('./pkcs12-pem-workspace/pkcs12-pem-workspace.vue'),
  icon: ToolIcon13,
});

const tool20 = defineTool({
  name: translate('tools.local-encrypted-otp-vault.title'),
  path: '/local-encrypted-otp-vault',
  description: translate('tools.local-encrypted-otp-vault.description'),
  keywords: ['OTP', 'TOTP', 'vault', 'AES-GCM', 'PBKDF2', 'IndexedDB', 'local', 'encrypted'],
  component: () => import('./local-encrypted-otp-vault/local-encrypted-otp-vault.vue'),
  icon: ToolIcon6,
});

const tool21 = defineTool({
  name: translate('tools.date-converter.title'),
  path: '/date-converter',
  description: translate('tools.date-converter.description'),
  keywords: ['date', 'time', 'converter', 'iso', 'utc', 'timezone', 'year', 'month', 'day', 'minute', 'seconde'],
  component: () => import('./date-time-converter/date-time-converter.vue'),
  icon: ToolIcon14,
});

const tool22 = defineTool({
  name: translate('tools.base-converter.title'),
  path: '/base-converter',
  description: translate('tools.base-converter.description'),
  keywords: ['integer', 'number', 'base', 'conversion', 'decimal', 'hexadecimal', 'binary', 'octal', 'base64'],
  component: () => import('./integer-base-converter/integer-base-converter.vue'),
  icon: ToolIcon15,
});

const tool23 = defineTool({
  name: translate('tools.roman-numeral-converter.title'),
  path: '/roman-numeral-converter',
  description: translate('tools.roman-numeral-converter.description'),
  keywords: ['roman', 'arabic', 'converter', 'X', 'I', 'V', 'L', 'C', 'D', 'M'],
  component: () => import('./roman-numeral-converter/roman-numeral-converter.vue'),
  icon: ToolIcon16,
});

const tool24 = defineTool({
  name: translate('tools.base64-string-converter.title'),
  path: '/base64-string-converter',
  description: translate('tools.base64-string-converter.description'),
  keywords: ['base64', 'converter', 'conversion', 'web', 'data', 'format', 'atob', 'btoa'],
  component: () => import('./base64-string-converter/base64-string-converter.vue'),
  icon: ToolIcon17,
  redirectFrom: ['/file-to-base64', '/base64-converter'],
});

const tool25 = defineTool({
  name: translate('tools.base64-file-converter.title'),
  path: '/base64-file-converter',
  description: translate('tools.base64-file-converter.description'),
  keywords: ['base64', 'converter', 'upload', 'image', 'file', 'conversion', 'web', 'data', 'format'],
  component: () => import('./base64-file-converter/base64-file-converter.vue'),
  icon: ToolIcon17,
});

const tool26 = defineTool({
  name: translate('tools.gzip-converter.title'),
  path: '/gzip-converter',
  description: translate('tools.gzip-converter.description'),
  keywords: ['gzip', 'compress', 'decompress', 'file', 'string', 'base64', 'compression stream'],
  component: () => import('./gzip-converter/gzip-converter.vue'),
  icon: ToolIcon17,
});

const tool27 = defineTool({
  name: translate('tools.idn-safety-converter.title'),
  path: '/idn-safety-converter',
  description: translate('tools.idn-safety-converter.description'),
  keywords: ['punycode', 'idn', 'domain', 'unicode', 'confusable', 'phishing', 'ace'],
  component: () => import('./idn-safety-converter/idn-safety-converter.vue'),
  icon: ToolIcon18,
});

const tool28 = defineTool({
  name: translate('tools.color-converter.title'),
  path: '/color-converter',
  description: translate('tools.color-converter.description'),
  keywords: ['color', 'converter', 'OKLab', 'OKLCH', 'gamut', 'sRGB'],
  component: () => import('./color-converter/color-converter.vue'),
  icon: ToolIcon19,
  redirectFrom: ['/color-picker-converter'],
});

const tool29 = defineTool({
  name: translate('tools.case-converter.title'),
  path: '/case-converter',
  description: translate('tools.case-converter.description'),
  keywords: [
    'case',
    'converter',
    'camelCase',
    'capitalCase',
    'constantCase',
    'dotCase',
    'headerCase',
    'noCase',
    'paramCase',
    'pascalCase',
    'pathCase',
    'sentenceCase',
    'snakeCase',
  ],
  component: () => import('./case-converter/case-converter.vue'),
  icon: ToolIcon20,
});

const tool30 = defineTool({
  name: translate('tools.text-to-nato-alphabet.title'),
  path: '/text-to-nato-alphabet',
  description: translate('tools.text-to-nato-alphabet.description'),
  keywords: ['string', 'nato', 'alphabet', 'phonetic', 'oral', 'transmission'],
  component: () => import('./text-to-nato-alphabet/text-to-nato-alphabet.vue'),
  icon: ToolIcon21,
});

const tool31 = defineTool({
  name: translate('tools.text-to-binary.title'),
  path: '/text-to-binary',
  description: translate('tools.text-to-binary.description'),
  keywords: ['text', 'to', 'binary', 'converter', 'encode', 'decode', 'ascii'],
  component: () => import('./text-to-binary/text-to-binary.vue'),
  icon: ToolIcon22,
  createdAt: new Date('2023-10-15'),
});

const tool32 = defineTool({
  name: translate('tools.text-to-unicode.title'),
  path: '/text-to-unicode',
  description: translate('tools.text-to-unicode.description'),
  keywords: ['text', 'to', 'unicode'],
  component: () => import('./text-to-unicode/text-to-unicode.vue'),
  icon: ToolIcon18,
  createdAt: new Date('2024-01-31'),
});

const tool33 = defineTool({
  name: translate('tools.yaml-to-json-converter.title'),
  path: '/yaml-to-json-converter',
  description: translate('tools.yaml-to-json-converter.description'),
  keywords: ['yaml', 'to', 'json'],
  component: () => import('./yaml-to-json-converter/yaml-to-json.vue'),
  icon: ToolIcon8,
  createdAt: new Date('2023-04-10'),
});

const tool34 = defineTool({
  name: translate('tools.yaml-to-toml.title'),
  path: '/yaml-to-toml',
  description: translate('tools.yaml-to-toml.description'),
  keywords: ['yaml', 'to', 'toml', 'convert', 'transform'],
  component: () => import('./yaml-to-toml/yaml-to-toml.vue'),
  icon: ToolIcon8,
  createdAt: new Date('2023-06-23'),
});

const tool35 = defineTool({
  name: translate('tools.json-to-yaml-converter.title'),
  path: '/json-to-yaml-converter',
  description: translate('tools.json-to-yaml-converter.description'),
  keywords: ['yaml', 'to', 'json'],
  component: () => import('./json-to-yaml-converter/json-to-yaml.vue'),
  icon: ToolIcon23,
  createdAt: new Date('2023-04-10'),
});

const tool36 = defineTool({
  name: translate('tools.json-to-toml.title'),
  path: '/json-to-toml',
  description: translate('tools.json-to-toml.description'),
  keywords: ['json', 'parse', 'toml', 'convert', 'transform'],
  component: () => import('./json-to-toml/json-to-toml.vue'),
  icon: ToolIcon23,
  createdAt: new Date('2023-06-23'),
});

const tool37 = defineTool({
  name: translate('tools.list-converter.title'),
  path: '/list-converter',
  description: translate('tools.list-converter.description'),
  keywords: ['list', 'converter', 'sort', 'reverse', 'prefix', 'suffix', 'lowercase', 'truncate'],
  component: () => import('./list-converter/list-converter.vue'),
  icon: ToolIcon24,
  createdAt: new Date('2023-05-07'),
});

const tool38 = defineTool({
  name: translate('tools.toml-to-json.title'),
  path: '/toml-to-json',
  description: translate('tools.toml-to-json.description'),
  keywords: ['toml', 'json', 'convert', 'online', 'transform', 'parser'],
  component: () => import('./toml-to-json/toml-to-json.vue'),
  icon: ToolIcon25,
  createdAt: new Date('2023-06-23'),
});

const tool39 = defineTool({
  name: translate('tools.toml-to-yaml.title'),
  path: '/toml-to-yaml',
  description: translate('tools.toml-to-yaml.description'),
  keywords: ['toml', 'yaml', 'convert', 'online', 'transform', 'parse'],
  component: () => import('./toml-to-yaml/toml-to-yaml.vue'),
  icon: ToolIcon25,
  createdAt: new Date('2023-06-23'),
});

const tool40 = defineTool({
  name: 'XML to JSON',
  path: '/xml-to-json',
  description: 'Convert XML to JSON',
  keywords: ['xml', 'json'],
  component: () => import('./xml-to-json/xml-to-json.vue'),
  icon: ToolIcon23,
  createdAt: new Date('2024-08-09'),
});

const tool41 = defineTool({
  name: 'JSON to XML',
  path: '/json-to-xml',
  description: 'Convert JSON to XML',
  keywords: ['json', 'xml'],
  component: () => import('./json-to-xml/json-to-xml.vue'),
  icon: ToolIcon23,
  createdAt: new Date('2024-08-09'),
});

const tool42 = defineTool({
  name: 'Markdown to HTML',
  path: '/markdown-to-html',
  description: 'Convert Markdown to Html and allow to print (as PDF)',
  keywords: ['markdown', 'html', 'converter', 'pdf'],
  component: () => import('./markdown-to-html/markdown-to-html.vue'),
  icon: ToolIcon26,
  createdAt: new Date('2024-08-25'),
});

const tool43 = defineTool({
  name: translate('tools.url-encoder.title'),
  path: '/url-encoder',
  description: translate('tools.url-encoder.description'),
  keywords: ['url', 'encode', 'decode', 'percent', '%20', 'format'],
  component: () => import('./url-encoder/url-encoder.vue'),
  icon: ToolIcon27,
});

const tool44 = defineTool({
  name: translate('tools.html-entities.title'),
  path: '/html-entities',
  description: translate('tools.html-entities.description'),
  keywords: ['html', 'entities', 'escape', 'unescape', 'special', 'characters', 'tags'],
  component: () => import('./html-entities/html-entities.vue'),
  icon: ToolIcon28,
});

const tool45 = defineTool({
  name: translate('tools.url-parser.title'),
  path: '/url-parser',
  description: translate('tools.url-parser.description'),
  keywords: ['url', 'parser', 'protocol', 'origin', 'params', 'port', 'username', 'password', 'href'],
  component: () => import('./url-parser/url-parser.vue'),
  icon: ToolIcon29,
});

const tool46 = defineTool({
  name: translate('tools.device-information.title'),
  path: '/device-information',
  description: translate('tools.device-information.description'),
  keywords: [
    'device',
    'information',
    'screen',
    'pixel',
    'ratio',
    'status',
    'data',
    'computer',
    'size',
    'user',
    'agent',
  ],
  component: () => import('./device-information/device-information.vue'),
  icon: ToolIcon30,
});

const tool47 = defineTool({
  name: translate('tools.basic-auth-generator.title'),
  path: '/basic-auth-generator',
  description: translate('tools.basic-auth-generator.description'),
  keywords: [
    'basic',
    'auth',
    'generator',
    'username',
    'password',
    'base64',
    'authentication',
    'header',
    'authorization',
  ],
  component: () => import('./basic-auth-generator/basic-auth-generator.vue'),
  icon: ToolIcon31,
});

const tool48 = defineTool({
  name: translate('tools.og-meta-generator.title'),
  path: '/og-meta-generator',
  description: translate('tools.og-meta-generator.description'),
  keywords: [
    'meta',
    'tag',
    'generator',
    'social',
    'title',
    'description',
    'image',
    'share',
    'online',
    'website',
    'open',
    'graph',
    'og',
  ],
  component: () => import('./meta-tag-generator/meta-tag-generator.vue'),
  icon: ToolIcon32,
});

const tool49 = defineTool({
  name: translate('tools.otp-generator.title'),
  path: '/otp-generator',
  description: translate('tools.otp-generator.description'),
  keywords: [
    'otp',
    'code',
    'generator',
    'validator',
    'one',
    'time',
    'password',
    'authentication',
    'MFA',
    'mobile',
    'device',
    'security',
    'TOTP',
    'HOTP',
    'counter',
    'Time',
    'HMAC',
  ],
  component: () => import('./otp-code-generator-and-validator/otp-code-generator-and-validator.vue'),
  icon: ToolIcon33,
});

const tool50 = defineTool({
  name: translate('tools.mime-types.title'),
  path: '/mime-types',
  description: translate('tools.mime-types.description'),
  keywords: ['mime', 'types', 'extension', 'content', 'type'],
  component: () => import('./mime-types/mime-types.vue'),
  icon: ToolIcon34,
});

const tool51 = defineTool({
  name: translate('tools.jwt-parser.title'),
  path: '/jwt-parser',
  description: translate('tools.jwt-parser.description'),
  keywords: [
    'jwt',
    'parser',
    'decode',
    'typ',
    'alg',
    'iss',
    'sub',
    'aud',
    'exp',
    'nbf',
    'iat',
    'jti',
    'json',
    'web',
    'token',
    'verify',
    'sign',
    'hmac',
    'HS256',
    'HS384',
    'HS512',
    'JWK',
    'JWKS',
    'RSA',
    'RSA-PSS',
    'ECDSA',
    'EdDSA',
    'Ed25519',
    'public key',
    'kid',
  ],
  component: () => import('./jwt-parser/jwt-parser.vue'),
  icon: ToolIcon11,
});

const tool52 = defineTool({
  name: translate('tools.keycode-info.title'),
  path: '/keycode-info',
  description: translate('tools.keycode-info.description'),
  keywords: [
    'keycode',
    'info',
    'code',
    'javascript',
    'event',
    'keycodes',
    'which',
    'keyboard',
    'press',
    'modifier',
    'alt',
    'ctrl',
    'meta',
    'shift',
  ],
  component: () => import('./keycode-info/keycode-info.vue'),
  icon: ToolIcon35,
});

const tool53 = defineTool({
  name: translate('tools.slugify-string.title'),
  path: '/slugify-string',
  description: translate('tools.slugify-string.description'),
  keywords: ['slugify', 'string', 'escape', 'emoji', 'special', 'character', 'space', 'trim'],
  component: () => import('./slugify-string/slugify-string.vue'),
  icon: ToolIcon36,
});

const tool54 = defineTool({
  name: translate('tools.html-wysiwyg-editor.title'),
  path: '/html-wysiwyg-editor',
  description: translate('tools.html-wysiwyg-editor.description'),
  keywords: ['html', 'wysiwyg', 'editor', 'p', 'ul', 'ol', 'converter', 'live'],
  component: () => import('./html-wysiwyg-editor/html-wysiwyg-editor.vue'),
  icon: ToolIcon37,
});

const tool55 = defineTool({
  name: translate('tools.user-agent-parser.title'),
  path: '/user-agent-parser',
  description: translate('tools.user-agent-parser.description'),
  keywords: ['user', 'agent', 'parser', 'browser', 'engine', 'os', 'cpu', 'device', 'user-agent', 'client'],
  component: () => import('./user-agent-parser/user-agent-parser.vue'),
  icon: ToolIcon38,
  createdAt: new Date('2023-04-06'),
});

const tool56 = defineTool({
  name: translate('tools.http-status-codes.title'),
  path: '/http-status-codes',
  description: translate('tools.http-status-codes.description'),
  keywords: [
    'http',
    'status',
    'codes',
    ...codesByCategories.flatMap(({ codes }) => codes.flatMap(({ code, name }) => [String(code), name])),
  ],
  component: () => import('./http-status-codes/http-status-codes.vue'),
  icon: ToolIcon39,
  createdAt: new Date('2023-04-13'),
});

const tool57 = defineTool({
  name: translate('tools.json-diff.title'),
  path: '/json-diff',
  description: translate('tools.json-diff.description'),
  keywords: ['json', 'diff', 'compare', 'difference', 'object', 'data'],
  component: () => import('./json-diff/json-diff.vue'),
  icon: ToolIcon40,
  createdAt: new Date('2023-04-20'),
});

const tool58 = defineTool({
  name: 'Outlook Safelink decoder',
  path: '/safelink-decoder',
  description: 'Decode Outlook SafeLink links',
  keywords: ['outlook', 'safelink', 'decoder'],
  component: () => import('./safelink-decoder/safelink-decoder.vue'),
  icon: ToolIcon41,
  createdAt: new Date('2024-03-11'),
});

const tool59 = defineTool({
  name: translate('tools.sensitive-data-masker.title'),
  path: '/sensitive-data-masker',
  description: translate('tools.sensitive-data-masker.description'),
  keywords: ['redact', 'mask', 'sanitize', 'har', 'secret', 'token', 'password', 'privacy', 'pii'],
  component: () => import('./sensitive-data-masker/sensitive-data-masker.vue'),
  icon: ToolIcon4,
});

const tool60 = defineTool({
  name: translate('tools.http-request-code-builder.title'),
  path: '/http-request-code-builder',
  description: translate('tools.http-request-code-builder.description'),
  keywords: ['http', 'request', 'curl', 'fetch', 'api', 'headers', 'query', 'code', 'redact'],
  component: () => import('./http-request-code-builder/http-request-code-builder.vue'),
  icon: ToolIcon27,
});

const tool61 = defineTool({
  name: translate('tools.qrcode-generator.title'),
  path: '/qrcode-generator',
  description: translate('tools.qrcode-generator.description'),
  keywords: ['qr', 'code', 'generator', 'square', 'color', 'link', 'low', 'medium', 'quartile', 'high', 'transparent'],
  component: () => import('./qr-code-generator/qr-code-generator.vue'),
  icon: ToolIcon42,
});

const tool62 = defineTool({
  name: translate('tools.qr-decoder-otp-import.title'),
  path: '/qr-decoder-otp-import',
  description: translate('tools.qr-decoder-otp-import.description'),
  keywords: ['qr', 'decoder', 'reader', 'camera', 'otp', 'totp', 'hotp', 'otpauth'],
  component: () => import('./qr-decoder-otp-import/qr-decoder-otp-import.vue'),
  icon: ToolIcon43,
});

const tool63 = defineTool({
  name: translate('tools.wifi-qrcode-generator.title'),
  path: '/wifi-qrcode-generator',
  description: translate('tools.wifi-qrcode-generator.description'),
  keywords: ['qr', 'code', 'generator', 'square', 'color', 'link', 'low', 'medium', 'quartile', 'high', 'transparent', 'wifi', 'WPA2', 'WPA3', 'SAE', 'SSID'],
  component: () => import('./wifi-qr-code-generator/wifi-qr-code-generator.vue'),
  icon: ToolIcon42,
  createdAt: new Date('2023-09-06'),
});

const tool64 = defineTool({
  name: translate('tools.barcode-generator-reader.title'),
  path: '/barcode-generator-reader',
  description: translate('tools.barcode-generator-reader.description'),
  keywords: ['barcode', 'code 128', 'ean-13', 'upc-a', 'scanner', 'reader', 'generator', 'image'],
  component: () => import('./barcode-generator-reader/barcode-generator-reader.vue'),
  icon: ToolIcon42,
});

const tool65 = defineTool({
  name: translate('tools.image-metadata-remover.title'),
  path: '/image-metadata-remover',
  description: translate('tools.image-metadata-remover.description'),
  keywords: ['image', 'exif', 'metadata', 'xmp', 'iptc', 'privacy', 'jpeg', 'png', 'webp'],
  component: () => import('./image-metadata-remover/image-metadata-remover.vue'),
  icon: ToolIcon44,
});

const tool66 = defineTool({
  name: translate('tools.favicon-app-icon-generator.title'),
  path: '/favicon-app-icon-generator',
  description: translate('tools.favicon-app-icon-generator.description'),
  keywords: ['favicon', 'app icon', 'pwa', 'manifest', 'apple touch icon', 'maskable', 'png', 'canvas'],
  component: () => import('./favicon-app-icon-generator/favicon-app-icon-generator.vue'),
  icon: ToolIcon44,
});

const tool67 = defineTool({
  name: translate('tools.svg-placeholder-generator.title'),
  path: '/svg-placeholder-generator',
  description: translate('tools.svg-placeholder-generator.description'),
  keywords: ['svg', 'placeholder', 'generator', 'image', 'size', 'mockup'],
  component: () => import('./svg-placeholder-generator/svg-placeholder-generator.vue'),
  icon: ToolIcon44,
});

const tool68 = defineTool({
  name: translate('tools.camera-recorder.title'),
  path: '/camera-recorder',
  description: translate('tools.camera-recorder.description'),
  keywords: ['camera', 'recoder'],
  component: () => import('./camera-recorder/camera-recorder.vue'),
  icon: ToolIcon45,
  createdAt: new Date('2023-05-15'),
});

const tool69 = defineTool({
  name: translate('tools.git-memo.title'),
  path: '/git-memo',
  description: translate('tools.git-memo.description'),
  keywords: ['git', 'push', 'force', 'pull', 'commit', 'amend', 'rebase', 'merge', 'reset', 'soft', 'hard', 'lease'],
  component: () => import('./git-memo/git-memo.vue'),
  icon: ToolIcon46,
});

const tool70 = defineTool({
  name: translate('tools.conventional-commit-helper.title'),
  path: '/conventional-commit-helper',
  description: translate('tools.conventional-commit-helper.description'),
  keywords: ['conventional commits', 'git', 'commit', 'semantic release', 'changelog', 'breaking change'],
  component: () => import('./conventional-commit-helper/conventional-commit-helper.vue'),
  icon: ToolIcon46,
});

const tool71 = defineTool({
  name: translate('tools.cli-command-editor.title'),
  path: '/cli-command-editor',
  description: translate('tools.cli-command-editor.description'),
  keywords: ['cli', 'command', 'shell', 'posix', 'powershell', 'quote', 'flags', 'pipeline', 'redirect'],
  component: () => import('./cli-command-editor/cli-command-editor.vue'),
  icon: ToolIcon47,
});

const tool72 = defineTool({
  name: translate('tools.devops-config-workspace.title'),
  path: '/devops-config-workspace',
  description: translate('tools.devops-config-workspace.description'),
  keywords: ['devops', 'dockerfile', 'compose', 'nginx', 'properties', 'yaml', 'json', 'toml', 'dotenv', '.env', 'environment variables', 'lint', 'format', 'config'],
  component: () => import('./devops-config-workspace/devops-config-workspace.vue'),
  icon: ToolIcon48,
});

const tool73 = defineTool({
  name: translate('tools.developer-text-workspace.title'),
  path: '/developer-text-workspace',
  description: translate('tools.developer-text-workspace.description'),
  keywords: ['stack trace', 'replace', 'regex', 'folder', 'tree', 'markdown', 'toc', 'text'],
  component: () => import('./developer-text-workspace/developer-text-workspace.vue'),
  icon: ToolIcon49,
});

const tool74 = defineTool({
  name: translate('tools.spdx-license-guidance.title'),
  path: '/spdx-license-guidance',
  description: translate('tools.spdx-license-guidance.description'),
  keywords: ['SPDX', 'license', 'compatibility', 'attribution', 'NOTICE', 'copyleft', 'GPL', 'MIT', 'Apache'],
  component: () => import('./spdx-license-guidance/spdx-license-guidance.vue'),
  icon: ToolIcon49,
});

const tool75 = defineTool({
  name: translate('tools.markdown-table-generator.title'),
  path: '/markdown-table-generator',
  description: translate('tools.markdown-table-generator.description'),
  keywords: ['markdown', 'table', 'csv', 'tsv', 'alignment', 'generator'],
  component: () => import('./markdown-table-generator/markdown-table-generator.vue'),
  icon: ToolIcon50,
});

const tool76 = defineTool({
  name: translate('tools.mermaid-diagram.title'),
  path: '/mermaid-diagram',
  description: translate('tools.mermaid-diagram.description'),
  keywords: ['mermaid', 'diagram', 'flowchart', 'sequence', 'class', 'state', 'entity relationship', 'svg', 'png'],
  component: () => import('./mermaid-diagram/mermaid-diagram.vue'),
  icon: ToolIcon51,
});

const tool77 = defineTool({
  name: translate('tools.tabular-data-inspector.title'),
  path: '/tabular-data-inspector',
  description: translate('tools.tabular-data-inspector.description'),
  keywords: ['CSV', 'TSV', 'table', 'tabular', 'inspect', 'import', 'JSON', 'spreadsheet', 'RFC 4180'],
  component: () => import('./tabular-data-inspector/tabular-data-inspector.vue'),
  icon: ToolIcon50,
});

const tool78 = defineTool({
  name: translate('tools.local-file-inspector.title'),
  path: '/local-file-inspector',
  description: translate('tools.local-file-inspector.description'),
  keywords: ['file', 'magic bytes', 'signature', 'mime', 'hex', 'crc32', 'inspect'],
  component: () => import('./local-file-inspector/local-file-inspector.vue'),
  icon: ToolIcon52,
});

const tool79 = defineTool({
  name: translate('tools.saml-enterprise-inspector.title'),
  path: '/saml-enterprise-inspector',
  description: translate('tools.saml-enterprise-inspector.description'),
  keywords: ['saml', 'assertion', 'base64', 'deflate', 'redirect', 'filetime', 'ldap', 'generalized time', 'active directory'],
  component: () => import('./saml-enterprise-inspector/saml-enterprise-inspector.vue'),
  icon: ToolIcon2,
});

const tool80 = defineTool({
  name: translate('tools.random-port-generator.title'),
  path: '/random-port-generator',
  description: translate('tools.random-port-generator.description'),
  keywords: ['system', 'port', 'lan', 'generator', 'random', 'development', 'computer'],
  component: () => import('./random-port-generator/random-port-generator.vue'),
  icon: ToolIcon53,
});

const tool81 = defineTool({
  name: translate('tools.crontab-generator.title'),
  path: '/crontab-generator',
  description: translate('tools.crontab-generator.description'),
  keywords: [
    'crontab',
    'generator',
    'cronjob',
    'cron',
    'schedule',
    'parse',
    'expression',
    'year',
    'month',
    'week',
    'day',
    'minute',
    'second',
  ],
  component: () => import('./crontab-generator/crontab-generator.vue'),
  icon: ToolIcon54,
});

const tool82 = defineTool({
  name: translate('tools.json-prettify.title'),
  path: '/json-prettify',
  description: translate('tools.json-prettify.description'),
  keywords: ['json', 'viewer', 'prettify', 'format'],
  component: () => import('./json-viewer/json-viewer.vue'),
  icon: ToolIcon23,
  redirectFrom: ['/json-viewer'],
});

const tool83 = defineTool({
  name: translate('tools.json-schema-validator.title'),
  path: '/json-schema-validator',
  description: translate('tools.json-schema-validator.description'),
  keywords: ['json', 'schema', 'validator', 'validation', 'draft 7', 'draft 2019-09', 'draft 2020-12'],
  component: () => import('./json-schema-validator/json-schema-validator.vue'),
  icon: ToolIcon55,
});

const tool84 = defineTool({
  name: translate('tools.json-minify.title'),
  path: '/json-minify',
  description: translate('tools.json-minify.description'),
  keywords: ['json', 'minify', 'format'],
  component: () => import('./json-minify/json-minify.vue'),
  icon: ToolIcon23,
});

const tool85 = defineTool({
  name: translate('tools.json-repair-query.title'),
  path: '/json-repair-query',
  description: translate('tools.json-repair-query.description'),
  keywords: ['json', 'repair', 'json5', 'jsonpath', 'query', 'jq', 'filter', 'extract', 'escaped json', 'unescape', 'logs'],
  component: () => import('./json-repair-query/json-repair-query.vue'),
  icon: ToolIcon23,
});

const tool86 = defineTool({
  name: translate('tools.json-code-generator.title'),
  path: '/json-code-generator',
  description: translate('tools.json-code-generator.description'),
  keywords: ['json', 'schema', 'typescript', 'code generation', 'inference', 'size', 'RFC 6902', 'JSON Patch', 'JSON Pointer', 'diff'],
  component: () => import('./json-code-generator/json-code-generator.vue'),
  icon: ToolIcon23,
});

const tool87 = defineTool({
  name: translate('tools.json-to-csv.title'),
  path: '/json-to-csv',
  description: translate('tools.json-to-csv.description'),
  keywords: ['json', 'to', 'csv', 'convert'],
  component: () => import('./json-to-csv/json-to-csv.vue'),
  icon: ToolIcon24,
  createdAt: new Date('2023-06-18'),
});

const tool88 = defineTool({
  name: translate('tools.sql-prettify.title'),
  path: '/sql-prettify',
  description: translate('tools.sql-prettify.description'),
  keywords: [
    'sql',
    'prettify',
    'beautify',
    'GCP BigQuery',
    'IBM DB2',
    'Apache Hive',
    'MariaDB',
    'MySQL',
    'Couchbase N1QL',
    'Oracle PL/SQL',
    'PostgreSQL',
    'Amazon Redshift',
    'Spark',
    'SQL Server Transact-SQL',
  ],
  component: () => import('./sql-prettify/sql-prettify.vue'),
  icon: ToolIcon50,
});

const tool89 = defineTool({
  name: translate('tools.chmod-calculator.title'),
  path: '/chmod-calculator',
  description: translate('tools.chmod-calculator.description'),
  keywords: [
    'chmod',
    'calculator',
    'file',
    'permission',
    'files',
    'directory',
    'folder',
    'recursive',
    'generator',
    'octal',
    'symbolic',
    'setuid',
    'setgid',
    'sticky',
    'umask',
  ],
  component: () => import('./chmod-calculator/chmod-calculator.vue'),
  icon: ToolIcon56,
});

const tool90 = defineTool({
  name: translate('tools.docker-run-to-docker-compose-converter.title'),
  path: '/docker-run-to-docker-compose-converter',
  description: translate('tools.docker-run-to-docker-compose-converter.description'),
  keywords: ['docker', 'run', 'compose', 'yaml', 'yml', 'convert', 'deamon'],
  component: () => import('./docker-run-to-docker-compose-converter/docker-run-to-docker-compose-converter.vue'),
  icon: ToolIcon57,
});

const tool91 = defineTool({
  name: translate('tools.xml-formatter.title'),
  path: '/xml-formatter',
  description: translate('tools.xml-formatter.description'),
  keywords: ['xml', 'prettify', 'format'],
  component: () => import('./xml-formatter/xml-formatter.vue'),
  icon: ToolIcon28,
  createdAt: new Date('2023-06-17'),
});

const tool92 = defineTool({
  name: translate('tools.yaml-prettify.title'),
  path: '/yaml-prettify',
  description: translate('tools.yaml-prettify.description'),
  keywords: ['yaml', 'viewer', 'prettify', 'format'],
  component: () => import('./yaml-viewer/yaml-viewer.vue'),
  icon: ToolIcon8,
  createdAt: new Date('2024-01-31'),
});

const tool93 = defineTool({
  name: 'Email normalizer',
  path: '/email-normalizer',
  description: 'Normalize email addresses to a standard format for easier comparison. Useful for deduplication and data cleaning.',
  keywords: ['email', 'normalizer'],
  component: () => import('./email-normalizer/email-normalizer.vue'),
  icon: ToolIcon58,
  createdAt: new Date('2024-08-15'),
});

const tool94 = defineTool({
  name: 'Regex Tester',
  path: '/regex-tester',
  description: 'Test your regular expressions with sample text.',
  keywords: ['regex', 'tester', 'sample', 'expression'],
  component: () => import('./regex-tester/regex-tester.vue'),
  icon: ToolIcon59,
  createdAt: new Date('2024-09-20'),
});

const tool95 = defineTool({
  name: 'Regex cheatsheet',
  path: '/regex-memo',
  description: 'Javascript Regex/Regular Expression cheatsheet',
  keywords: ['regex', 'regular', 'expression', 'javascript', 'memo', 'cheatsheet'],
  component: () => import('./regex-memo/regex-memo.vue'),
  icon: ToolIcon60,
  createdAt: new Date('2024-09-20'),
});

const tool96 = defineTool({
  name: translate('tools.openapi-inspector.title'),
  path: '/openapi-inspector',
  description: translate('tools.openapi-inspector.description'),
  keywords: ['OpenAPI', 'Swagger', 'API', 'endpoint', 'schema', 'JSON', 'YAML', 'curl', 'mock', 'request', 'local', 'inspector'],
  component: () => import('./openapi-inspector/openapi-inspector.vue'),
  icon: ToolIcon61,
});

const tool97 = defineTool({
  name: translate('tools.ipv4-subnet-calculator.title'),
  path: '/ipv4-subnet-calculator',
  description: translate('tools.ipv4-subnet-calculator.description'),
  keywords: ['ipv4', 'subnet', 'calculator', 'mask', 'network', 'cidr', 'netmask', 'bitmask', 'broadcast', 'address'],
  component: () => import('./ipv4-subnet-calculator/ipv4-subnet-calculator.vue'),
  icon: ToolIcon62,
});

const tool98 = defineTool({
  name: translate('tools.ipv4-address-converter.title'),
  path: '/ipv4-address-converter',
  description: translate('tools.ipv4-address-converter.description'),
  keywords: ['ipv4', 'address', 'converter', 'decimal', 'hexadecimal', 'binary', 'ipv6'],
  component: () => import('./ipv4-address-converter/ipv4-address-converter.vue'),
  icon: ToolIcon22,
  createdAt: new Date('2023-04-08'),
});

const tool99 = defineTool({
  name: translate('tools.ipv4-range-expander.title'),
  path: '/ipv4-range-expander',
  description: translate('tools.ipv4-range-expander.description'),
  keywords: ['ipv4', 'range', 'expander', 'subnet', 'creator', 'cidr'],
  component: () => import('./ipv4-range-expander/ipv4-range-expander.vue'),
  icon: ToolIcon63,
  createdAt: new Date('2023-04-19'),
});

const tool100 = defineTool({
  name: translate('tools.ipv6-calculator.title'),
  path: '/ipv6-calculator',
  description: translate('tools.ipv6-calculator.description'),
  keywords: ['ipv6', 'cidr', 'subnet', 'network', 'range', 'compress', 'expand', 'membership', 'bigint'],
  component: () => import('./ipv6-calculator/ipv6-calculator.vue'),
  icon: ToolIcon62,
});

const tool101 = defineTool({
  name: translate('tools.network-calculation-suite.title'),
  path: '/network-calculation-suite',
  description: translate('tools.network-calculation-suite.description'),
  keywords: ['network', 'ipv4', 'ipv6', 'cidr', 'exclude', 'dhcp', 'option 43', 'port', 'ttl'],
  component: () => import('./network-calculation-suite/network-calculation-suite.vue'),
  icon: ToolIcon62,
});

const tool102 = defineTool({
  name: translate('tools.dns-over-https-query.title'),
  path: '/dns-over-https-query',
  description: translate('tools.dns-over-https-query.description'),
  keywords: ['dns', 'doh', 'https', 'resolver', 'record', 'a', 'aaaa', 'cname', 'mx', 'txt', 'ns', 'soa', 'ptr', 'srv', 'caa'],
  component: () => import('./dns-over-https-query/dns-over-https-query.vue'),
  icon: ToolIcon62,
});

const tool103 = defineTool({
  name: translate('tools.mac-address-lookup.title'),
  path: '/mac-address-lookup',
  description: translate('tools.mac-address-lookup.description'),
  keywords: ['mac', 'address', 'lookup', 'vendor', 'parser', 'manufacturer'],
  component: () => import('./mac-address-lookup/mac-address-lookup.vue'),
  icon: ToolIcon64,
  createdAt: new Date('2023-04-06'),
});

const tool104 = defineTool({
  name: translate('tools.mac-address-generator.title'),
  path: '/mac-address-generator',
  description: translate('tools.mac-address-generator.description'),
  keywords: ['mac', 'address', 'generator', 'random', 'prefix'],
  component: () => import('./mac-address-generator/mac-address-generator.vue'),
  icon: ToolIcon64,
  createdAt: new Date('2023-11-31'),
});

const tool105 = defineTool({
  name: translate('tools.ipv6-ula-generator.title'),
  path: '/ipv6-ula-generator',
  description: translate('tools.ipv6-ula-generator.description'),
  keywords: ['ipv6', 'ula', 'generator', 'rfc4193', 'network', 'private'],
  component: () => import('./ipv6-ula-generator/ipv6-ula-generator.vue'),
  icon: ToolIcon65,
  createdAt: new Date('2023-04-09'),
});

const tool106 = defineTool({
  name: translate('tools.offline-geoip-inspector.title'),
  path: '/offline-geoip-inspector',
  description: translate('tools.offline-geoip-inspector.description'),
  keywords: ['GeoIP', 'IP', 'country', 'IPv4', 'IPv6', 'offline', 'local', 'PDDL'],
  component: () => import('./offline-geoip-inspector/offline-geoip-inspector.vue'),
  icon: ToolIcon66,
});

const tool107 = defineTool({
  name: translate('tools.math-evaluator.title'),
  path: '/math-evaluator',
  description: translate('tools.math-evaluator.description'),
  keywords: [
    'math',
    'evaluator',
    'calculator',
    'expression',
    'abs',
    'acos',
    'acosh',
    'acot',
    'acoth',
    'acsc',
    'acsch',
    'asec',
    'asech',
    'asin',
    'asinh',
    'atan',
    'atan2',
    'atanh',
    'cos',
    'cosh',
    'cot',
    'coth',
    'csc',
    'csch',
    'sec',
    'sech',
    'sin',
    'sinh',
    'sqrt',
    'tan',
    'tanh',
  ],
  component: () => import('./math-evaluator/math-evaluator.vue'),
  icon: ToolIcon67,
});

const tool108 = defineTool({
  name: translate('tools.ieee754-inspector.title'),
  path: '/ieee754-inspector',
  description: translate('tools.ieee754-inspector.description'),
  keywords: ['ieee 754', 'float', 'double', 'binary32', 'binary64', 'rounding', 'nan', 'subnormal', 'endian'],
  component: () => import('./ieee754-inspector/ieee754-inspector.vue'),
  icon: ToolIcon67,
});

const tool109 = defineTool({
  name: translate('tools.eta-calculator.title'),
  path: '/eta-calculator',
  description: translate('tools.eta-calculator.description'),
  keywords: ['eta', 'calculator', 'estimated', 'time', 'arrival', 'average'],
  component: () => import('./eta-calculator/eta-calculator.vue'),
  icon: ToolIcon68,
});

const tool110 = defineTool({
  name: translate('tools.percentage-calculator.title'),
  path: '/percentage-calculator',
  description: translate('tools.percentage-calculator.description'),
  keywords: ['percentage', 'calculator', 'calculate', 'value', 'number', '%'],
  component: () => import('./percentage-calculator/percentage-calculator.vue'),
  icon: ToolIcon69,
  createdAt: new Date('2023-06-18'),
});

const tool111 = defineTool({
  name: translate('tools.chronometer.title'),
  path: '/chronometer',
  description: translate('tools.chronometer.description'),
  keywords: ['chronometer', 'time', 'lap', 'duration', 'measure', 'pause', 'resume', 'stopwatch'],
  component: () => import('./chronometer/chronometer.vue'),
  icon: ToolIcon70,
});

const tool112 = defineTool({
  name: translate('tools.timezone-duration-calculator.title'),
  path: '/timezone-duration-calculator',
  description: translate('tools.timezone-duration-calculator.description'),
  keywords: ['timezone', 'time zone', 'date', 'duration', 'dst', 'utc', 'convert', 'elapsed'],
  component: () => import('./timezone-duration-calculator/timezone-duration-calculator.vue'),
  icon: ToolIcon14,
});

const tool113 = defineTool({
  name: translate('tools.date-calendar-utilities.title'),
  path: '/date-calendar-utilities',
  description: translate('tools.date-calendar-utilities.description'),
  keywords: ['date', 'iso week', 'weekday', 'icalendar', 'ics', 'rfc 5545', 'vevent', 'calendar'],
  component: () => import('./date-calendar-utilities/date-calendar-utilities.vue'),
  icon: ToolIcon14,
});

const tool114 = defineTool({
  name: translate('tools.temperature-converter.title'),
  path: '/temperature-converter',
  description: translate('tools.temperature-converter.description'),
  keywords: [
    'temperature',
    'converter',
    'degree',
    'Kelvin',
    'Celsius',
    'Fahrenheit',
    'Rankine',
    'Delisle',
    'Newton',
    'Réaumur',
    'Rømer',
  ],
  component: () => import('./temperature-converter/temperature-converter.vue'),
  icon: ToolIcon71,
});

const tool115 = defineTool({
  name: translate('tools.data-units-converter.title'),
  path: '/data-units-converter',
  description: translate('tools.data-units-converter.description'),
  keywords: ['data', 'storage', 'transfer', 'bit', 'byte', 'si', 'iec', 'kibibyte', 'bandwidth'],
  component: () => import('./data-units-converter/data-units-converter.vue'),
  icon: ToolIcon72,
});

const tool116 = defineTool({
  name: translate('tools.raid-storage-calculator.title'),
  path: '/raid-storage-calculator',
  description: translate('tools.raid-storage-calculator.description'),
  keywords: ['raid', 'storage', 'disk', 'hdd', 'ssd', 'capacity', 'parity', 'mirror', 'failure'],
  component: () => import('./raid-storage-calculator/raid-storage-calculator.vue'),
  icon: ToolIcon72,
});

const tool117 = defineTool({
  name: translate('tools.benchmark-builder.title'),
  path: '/benchmark-builder',
  description: translate('tools.benchmark-builder.description'),
  keywords: ['benchmark', 'builder', 'execution', 'duration', 'mean', 'variance'],
  component: () => import('./benchmark-builder/benchmark-builder.vue'),
  icon: ToolIcon72,
  createdAt: new Date('2023-04-05'),
});

const tool118 = defineTool({
  name: translate('tools.mock-data-generator.title'),
  path: '/mock-data-generator',
  description: translate('tools.mock-data-generator.description'),
  keywords: ['faker', 'fake', 'mock', 'fixture', 'sample data', 'json', 'csv', 'seed', 'person', 'address'],
  component: () => import('./mock-data-generator/mock-data-generator.vue'),
  icon: ToolIcon23,
});

const tool119 = defineTool({
  name: translate('tools.lorem-ipsum-generator.title'),
  path: '/lorem-ipsum-generator',
  description: translate('tools.lorem-ipsum-generator.description'),
  keywords: ['lorem', 'ipsum', 'dolor', 'sit', 'amet', 'placeholder', 'text', 'filler', 'random', 'generator'],
  component: () => import('./lorem-ipsum-generator/lorem-ipsum-generator.vue'),
  icon: ToolIcon8,
});

const tool120 = defineTool({
  name: translate('tools.text-statistics.title'),
  path: '/text-statistics',
  description: translate('tools.text-statistics.description'),
  keywords: ['text', 'statistics', 'length', 'characters', 'count', 'size', 'bytes'],
  component: () => import('./text-statistics/text-statistics.vue'),
  icon: ToolIcon49,
  redirectFrom: ['/text-stats'],
});

const tool121 = defineTool({
  name: translate('tools.list-comparison.title'),
  path: '/list-comparison',
  description: translate('tools.list-comparison.description'),
  keywords: ['list', 'compare', 'set', 'multiset', 'duplicates', 'ordered', 'lcs'],
  component: () => import('./list-comparison/list-comparison.vue'),
  icon: ToolIcon24,
});

const tool122 = defineTool({
  name: translate('tools.unicode-gsm-inspector.title'),
  path: '/unicode-gsm-inspector',
  description: translate('tools.unicode-gsm-inspector.description'),
  keywords: ['unicode', 'code point', 'utf-8', 'utf-16', 'grapheme', 'gsm-7', 'sms', 'septet'],
  component: () => import('./unicode-gsm-inspector/unicode-gsm-inspector.vue'),
  icon: ToolIcon18,
});

const tool123 = defineTool({
  name: translate('tools.markdown-diff.title'),
  path: '/markdown-diff',
  description: translate('tools.markdown-diff.description'),
  keywords: ['markdown', 'md', 'diff', 'compare', 'line', 'word', 'preview'],
  component: () => import('./markdown-diff/markdown-diff.vue'),
  icon: ToolIcon73,
});

const tool124 = defineTool({
  name: translate('tools.emoji-picker.title'),
  path: '/emoji-picker',
  description: translate('tools.emoji-picker.description'),
  keywords: ['emoji', 'picker', 'unicode', 'copy', 'paste'],
  component: () => import('./emoji-picker/emoji-picker.vue'),
  icon: ToolIcon74,
  createdAt: new Date('2023-08-07'),
});

const tool125 = defineTool({
  name: translate('tools.string-obfuscator.title'),
  path: '/string-obfuscator',
  description: translate('tools.string-obfuscator.description'),
  keywords: ['string', 'obfuscator', 'secret', 'token', 'hide', 'obscure', 'mask', 'masking'],
  component: () => import('./string-obfuscator/string-obfuscator.vue'),
  icon: ToolIcon4,
  createdAt: new Date('2023-08-16'),
});

const tool126 = defineTool({
  name: translate('tools.text-diff.title'),
  path: '/text-diff',
  description: translate('tools.text-diff.description'),
  keywords: ['text', 'diff', 'compare', 'string', 'text diff', 'code'],
  component: () => import('./text-diff/text-diff.vue'),
  icon: ToolIcon73,
  createdAt: new Date('2023-08-16'),
});

const tool127 = defineTool({
  name: translate('tools.numeronym-generator.title'),
  path: '/numeronym-generator',
  description: translate('tools.numeronym-generator.description'),
  keywords: ['numeronym', 'generator', 'abbreviation', 'i18n', 'a11y', 'l10n'],
  component: () => import('./numeronym-generator/numeronym-generator.vue'),
  icon: ToolIcon75,
  createdAt: new Date('2023-11-05'),
});

const tool128 = defineTool({
  name: 'ASCII Art Text Generator',
  path: '/ascii-text-drawer',
  description: 'Create ASCII art text with many fonts and styles.',
  keywords: ['ascii', 'asciiart', 'text', 'drawer'],
  component: () => import('./ascii-text-drawer/ascii-text-drawer.vue'),
  icon: ToolIcon76,
  createdAt: new Date('2024-03-03'),
});

const tool129 = defineTool({
  name: translate('tools.parquet-reader.title'),
  path: '/parquet-reader',
  description: translate('tools.parquet-reader.description'),
  keywords: ['parquet', 'apache parquet', 'columnar', 'data', 'schema', 'metadata', 'csv', 'json'],
  component: () => import('./parquet-reader/parquet-reader.vue'),
  icon: ToolIcon77,
});

const tool130 = defineTool({
  name: translate('tools.xlsx-reader.title'),
  path: '/xlsx-reader',
  description: translate('tools.xlsx-reader.description'),
  keywords: ['xlsx', 'excel', 'spreadsheet', 'workbook', 'worksheet', 'table', 'csv', 'json'],
  component: () => import('./xlsx-reader/xlsx-reader.vue'),
  icon: ToolIcon78,
});

const tool131 = defineTool({
  name: translate('tools.phone-parser-and-formatter.title'),
  path: '/phone-parser-and-formatter',
  description: translate('tools.phone-parser-and-formatter.description'),
  keywords: [
    'phone',
    'parser',
    'formatter',
    'validate',
    'format',
    'number',
    'telephone',
    'mobile',
    'cell',
    'international',
    'national',
  ],
  component: () => import('./phone-parser-and-formatter/phone-parser-and-formatter.vue'),
  icon: ToolIcon79,
  createdAt: new Date('2023-05-01'),
});

const tool132 = defineTool({
  name: translate('tools.iban-validator-and-parser.title'),
  path: '/iban-validator-and-parser',
  description: translate('tools.iban-validator-and-parser.description'),
  keywords: ['iban', 'validator', 'and', 'parser', 'bic', 'bank'],
  component: () => import('./iban-validator-and-parser/iban-validator-and-parser.vue'),
  icon: ToolIcon80,
  createdAt: new Date('2023-08-26'),
});

export const toolsByCategory: ToolCategory[] = [
  { name: 'Crypto', components: [tool0, tool1, tool2, tool3, tool4, tool5, tool6, tool7, tool8, tool9, tool10, tool11, tool12, tool13, tool14, tool15, tool16, tool17, tool18, tool19, tool20] },
  { name: 'Converter', components: [tool21, tool22, tool23, tool24, tool25, tool26, tool27, tool28, tool29, tool30, tool31, tool32, tool33, tool34, tool35, tool36, tool37, tool38, tool39, tool40, tool41, tool42] },
  { name: 'Web', components: [tool43, tool44, tool45, tool46, tool47, tool48, tool49, tool50, tool51, tool52, tool53, tool54, tool55, tool56, tool57, tool58, tool59, tool60] },
  { name: 'Images and videos', components: [tool61, tool62, tool63, tool64, tool65, tool66, tool67, tool68] },
  { name: 'Development', components: [tool69, tool70, tool71, tool72, tool73, tool74, tool75, tool76, tool77, tool78, tool79, tool80, tool81, tool82, tool83, tool84, tool85, tool86, tool87, tool88, tool89, tool90, tool91, tool92, tool93, tool94, tool95, tool96] },
  { name: 'Network', components: [tool97, tool98, tool99, tool100, tool101, tool102, tool103, tool104, tool105, tool106] },
  { name: 'Math', components: [tool107, tool108, tool109, tool110] },
  { name: 'Measurement', components: [tool111, tool112, tool113, tool114, tool115, tool116, tool117] },
  { name: 'Text', components: [tool118, tool119, tool120, tool121, tool122, tool123, tool124, tool125, tool126, tool127, tool128] },
  { name: 'Data', components: [tool129, tool130, tool131, tool132] },
];

export const tools = toolsByCategory.flatMap(({ components }) => components);
